"""Shared pytest fixtures/bootstrapping for the case1 test suite.

Some tests (test_prescription_adversarial.py::test_spot_spraying_...) read
static fixture artifacts from ``case1/output/e2e_simulation/`` that are
generated by ``scripts/e2e_pipeline_simulation.py`` and intentionally kept
out of git (see .gitignore) because they are reproducible build output, not
source. This autouse, session-scoped fixture regenerates them once before
the test session (always, so stale output from an older generator cannot mask
regressions), so a fresh checkout (`make test`) is
green without any manual steps.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

ROOT_DIR = Path(__file__).resolve().parents[2]
E2E_OUTPUT_DIR = ROOT_DIR / "case1" / "output" / "e2e_simulation"
SIMULATION_SCRIPT = ROOT_DIR / "scripts" / "e2e_pipeline_simulation.py"


@pytest.fixture(scope="session", autouse=True)
def ensure_e2e_simulation_fixture():
    """Regenerate case1/output/e2e_simulation/* before the session."""
    if SIMULATION_SCRIPT.exists():
        subprocess.run(
            [sys.executable, str(SIMULATION_SCRIPT), "--output", str(E2E_OUTPUT_DIR)],
            cwd=str(ROOT_DIR),
            capture_output=True,
            text=True,
            check=False,
        )
    yield
